/**
 * Ports of the FIRST-CREDENTIAL half (AU-021, AU-026..AU-029, D-013).
 *
 * A THIRD PORTS FILE, and not more methods on either of the other two. The
 * session half (`ports.ts`) verifies credentials that already exist; the
 * administration half (`admin-ports.ts`) answers to somebody holding
 * `user:manage`. This half straddles them: an administrator issues the
 * invitation, and a person who CANNOT SIGN IN redeems it anonymously. Folding
 * it into either would put a public, unauthenticated flow behind a name that
 * says otherwise.
 *
 * WHAT IS DELIBERATELY ABSENT: any method returning a token. Tokens are
 * generated by the caller and only their hash crosses this boundary, so there
 * is no shape here that could accidentally read one back out of the database —
 * because there is none in the database to read.
 */

/** A stored invitation, as the rules need to see it. Never the token. */
export interface StoredCredentialInvitation {
  id: string;
  userId: string;
  expiresAt: Date;
  /** `null` = live. Set on redemption and on being superseded (AU-027). */
  usedAt: Date | null;
}

/**
 * AU-021, AU-026, AU-027. Carries the hash of the token, never the token: it
 * exists in memory for one HTTP response and nowhere else.
 */
export interface IssueCredentialInvitationInput {
  userId: string;
  /** SHA-256 of the token. The token itself never reaches persistence. */
  tokenHash: string;
  expiresAt: Date;
  /** Who invited them. `null` only for a seed, which has no author. */
  createdById: string | null;
  /** Stamped on the invitation this call supersedes, and on the new row. */
  now: Date;
}

/**
 * Everything the invitation use cases need from the person being invited.
 *
 * IT CARRIES THE CLINIC'S NAME, which does not belong to `auth`. That is
 * deliberate and it is the smaller of two evils: the message has to name the
 * clinic — an anonymous link asking for a password is indistinguishable from
 * phishing — and no module may import another, so the alternatives were a
 * shared «who is this clinic» port used by exactly one caller, or one extra
 * join in the query that is already being made. The adapter reads
 * `establishment.legal_name`; if a second consumer ever appears, that is when
 * the concept earns a home in `shared/`.
 */
export interface CredentialRecipient {
  userId: string;
  email: string;
  firstName: string;
  lastName: string;
  /** For the password policy: a password may not contain the owner's cedula. */
  cedula: string | null;
  /** Whose display name goes in the message. `null` when nobody is recorded. */
  inviterName: string | null;
  /** `null` on an installation with no establishment registered yet (OR-001). */
  clinicName: string | null;
}

/**
 * Persistence of first-credential invitations (D-013). No method returns or
 * accepts a plaintext token; lookups are by its SHA-256.
 */
export interface CredentialInvitationRepositoryPort {
  /**
   * Supersedes any live invitation of this account and issues a new one, in
   * ONE transaction (AU-027).
   *
   * Expressed as a single operation because the atomicity IS the requirement:
   * a link sent by mistake has to stop working, and «invalidate» followed by
   * «issue» as two calls leaves a window where a failure between them cancels
   * the person's only way in, or — worse, under the partial unique index —
   * lets a concurrent pair leave two live links.
   */
  supersedeAndIssue(input: IssueCredentialInvitationInput): Promise<void>;

  /** `null` when no invitation carries this hash. */
  findByTokenHash(
    tokenHash: string,
  ): Promise<StoredCredentialInvitation | null>;

  /**
   * Redeems the invitation and sets the account's password, or does neither.
   *
   * Returns `false` when the row was no longer live, which is how a RACE is
   * refused: two submissions of the same form must not both set a password,
   * and only one of them can win a conditional update. Reading first and
   * writing after would let both through, and the second would silently
   * overwrite the password the person had just chosen with the one they typed
   * in a stale tab.
   *
   * Every open session of the account is revoked in the same transaction, for
   * the reason `rotateCredentials` already exists: setting a credential and
   * cutting the sessions must not come apart.
   */
  redeem(input: {
    invitationId: string;
    userId: string;
    passwordHash: string;
    now: Date;
  }): Promise<boolean>;

  /** `null` when the account does not exist. */
  recipient(userId: string, inviterId: string | null): Promise<CredentialRecipient | null>; // prettier-ignore
}

export const CREDENTIAL_INVITATION_REPOSITORY = Symbol(
  'CREDENTIAL_INVITATION_REPOSITORY',
);

/**
 * Generating the token and hashing it.
 *
 * A PORT rather than a direct call to `TokenService`, because the application
 * layer may not import infrastructure — and reusing the session's token
 * generator is a decision worth being able to change: what these two need
 * happens to coincide today (256 bits of entropy, SHA-256 at rest), and
 * nothing says a credential link must follow a refresh token for ever.
 */
export interface CredentialTokenPort {
  /** A fresh opaque token and the hash that will be stored in its place. */
  generate(): { token: string; hash: string };
  /** The hash of a token presented by a caller, for the lookup. */
  hash(token: string): string;
}

export const CREDENTIAL_TOKENS = Symbol('CREDENTIAL_TOKENS');

/**
 * Where the interface lives, so a link can point at a screen and not at JSON.
 *
 * A VALUE TOKEN AND NOT A PORT, deliberately. What the use case depends on is
 * one string; wrapping it in an interface with a single `get()` would be a
 * pattern added for symmetry with its neighbours rather than to solve
 * anything. It is a token and not a `ConfigService` injection so the
 * application layer still does not know NestJS configuration exists — the
 * module reads `WEB_BASE_URL` from the validated environment and hands the
 * value over.
 */
export const WEB_BASE_URL = Symbol('WEB_BASE_URL');
