import { generateKeyPairSync } from 'node:crypto';

import forge from 'node-forge';

/**
 * A PKCS#12 GENERATED BY THE TEST ITSELF, never the author's certificate.
 *
 * Self-signed, RSA 2048 —what ARCOTEL-accredited entities issue— with the
 * validity the caller asks for, measured from the caller's clock. The key pair
 * comes from `node:crypto` because forge's pure-JS RSA generation takes
 * seconds per key.
 */
export interface TestPkcs12 {
  pkcs12: Buffer;
  password: string;
  certificatePem: string;
  subjectCommonName: string;
  serialNumber: string;
  notBefore: Date;
  notAfter: Date;
}

let serial = 0;

export function createTestPkcs12(options: {
  now: Date;
  /** Days from `now`; negative for a certificate already expired. */
  validFromDays?: number;
  validForDays?: number;
  password?: string;
  commonName?: string;
}): TestPkcs12 {
  const password = options.password ?? 'clave-de-prueba';
  const commonName = options.commonName ?? 'FIRMANTE DE PRUEBA';
  const day = 86_400_000;
  const notBefore = new Date(
    options.now.getTime() + (options.validFromDays ?? -1) * day,
  );
  const notAfter = new Date(
    notBefore.getTime() + (options.validForDays ?? 365) * day,
  );

  const { privateKey, publicKey } = generateKeyPairSync('rsa', {
    modulusLength: 2048,
  });
  const forgePrivate = forge.pki.privateKeyFromPem(
    privateKey.export({ type: 'pkcs1', format: 'pem' }).toString(),
  );
  const forgePublic = forge.pki.publicKeyFromPem(
    publicKey.export({ type: 'spki', format: 'pem' }).toString(),
  );

  serial += 1;
  const certificate = forge.pki.createCertificate();
  certificate.publicKey = forgePublic;
  certificate.serialNumber = String(serial).padStart(2, '0');
  certificate.validity.notBefore = notBefore;
  certificate.validity.notAfter = notAfter;
  const subject = [
    { name: 'commonName', value: commonName },
    { name: 'countryName', value: 'EC' },
    { name: 'organizationName', value: 'ENTIDAD DE PRUEBA' },
  ];
  certificate.setSubject(subject);
  certificate.setIssuer(subject);
  certificate.sign(forgePrivate, forge.md.sha256.create());

  const asn1 = forge.pkcs12.toPkcs12Asn1(
    forgePrivate,
    [certificate],
    password,
    {
      algorithm: '3des',
    },
  );
  const der = forge.asn1.toDer(asn1).getBytes();

  return {
    pkcs12: Buffer.from(der, 'binary'),
    password,
    certificatePem: forge.pki.certificateToPem(certificate),
    subjectCommonName: commonName,
    serialNumber: certificate.serialNumber,
    notBefore,
    notAfter,
  };
}
