import { admitsPrescribing } from '../domain/prescription';
import { Injectable } from '@nestjs/common';
import { Prisma } from '@prisma/client';

import { chartScope } from '../../../shared/infrastructure/prisma/patient-chart-scope';
import { PrismaService } from '../../../shared/infrastructure/prisma/prisma.service';
import { assertOffFormularyJustified } from '../domain/prescription-content';
import {
  ConceptNotPrescribableError,
  ControlledSubstanceNotPrescribableError,
  PrescriptionEncounterNotFoundError,
  PrescriptionEncounterNotOpenError,
  PrescriptionNotEditableError,
  PrescriptionNotFoundError,
} from '../domain/prescription.errors';
import type { ItemContent } from '../domain/prescription-content';
import type { PrescriptionStatus } from '../domain/prescription';
import type {
  DiscardPlan,
  EncounterPrescriptionsQuery,
  IssuePlan,
  IssueSnapshot,
  NewPrescription,
  PrescribingEncounter,
  PrescriberIdentity,
  PrescriptionQuery,
  PrescriptionRecordSource,
  PrescriptionRepository,
  PrescriptionView,
  SiteScopeFilter,
} from '../domain/prescription.repository';

/**
 * The prescription's rows in, domain shapes out.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * WHY EVERY CHECK IS INSIDE THE TRANSACTION THAT WRITES
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Four things can change between a read and a write here: a catalogue release
 * lands and retires the CNMB concept, an allergy is recorded while the doctor
 * types, an ACESS registration lapses at midnight, a colleague issues the same
 * draft. A caller who could ask any of them first and act later is the race
 * AG-045 was left open by — and here that race issues a prescription for the
 * substance an allergy was recorded for one second earlier.
 *
 * ⚠️ AND THE ADAPTER IS NOT THE GUARANTEE FOR TWO OF THEM.
 * `prescription_item_off_formulary` and `prescription_issued_coherence` are
 * `CHECK`s: they also stop an import, a `psql` and a use case somebody writes
 * in two years. What this file adds is the SENTENCE — the order
 * `NOTE_ALREADY_SIGNED` set in `encounter`: database first as the rule,
 * application second as the explanation.
 */

/** PR-007. The catalogue a prescribed medicine has to come from. */
const CNMB = 'CNMB';

/** One prescription line with the medicine data frozen on it. */
const ITEM_SELECT = {
  id: true,
  conceptId: true,
  // PR-008. Frozen from the concept read in the write's own transaction.
  genericName: true,
  presentation: true,
  concentration: true,
  routeCode: true,
  quantity: true,
  doseText: true,
  frequencyText: true,
  durationDays: true,
  instructions: true,
  offFormularyJustification: true,
} satisfies Prisma.PrescriptionItemSelect;

const PRESCRIPTION_SELECT = {
  id: true,
  encounterId: true,
  prescriberId: true,
  status: true,
  issuedAt: true,
  verificationCode: true,
  sequenceNumber: true,
  warningSigns: true,
  nonPharmacologicalAdvice: true,
  createdAt: true,
  // PR-011. The three columns of the discard register, minus the account:
  // `discarded_by_id` is the accountable «quién» and belongs in the trail, not
  // on every screen that lists a prescription (PR-092).
  discardedAt: true,
  discardReason: true,
  items: {
    /**
     * ⚠️ **Falta esquema** (PR-032). `prescription_item` HAS NO ORDER COLUMN,
     * so the line number a message addresses — «falta la concentración en la
     * línea 2» — is the position in this ordering and nothing else. `id` is a
     * `uuidv7()` generated by PostgreSQL 18, whose sub-millisecond precision
     * makes it monotonic in practice for rows inserted one after another, so
     * the order is the order they were written. «In practice» is exactly why it
     * is written down: a `line_number` column would make it a guarantee, and
     * until then two lines created inside the same 244 nanoseconds could swap.
     */
    orderBy: { id: 'asc' },
    select: ITEM_SELECT,
  },
} satisfies Prisma.PrescriptionSelect;

/** The shape `PRESCRIPTION_SELECT` produces. */
type PrescriptionRow = Prisma.PrescriptionGetPayload<{
  select: typeof PRESCRIPTION_SELECT;
}>;

/** What one statement can say about a concept, in the context of an attention. */
interface ConceptRow {
  id: string;
  system_code: string;
  display: string;
  in_force: boolean;
  /** PR-070. `attributes.controlled` of the CNMB concept. */
  controlled: boolean;
}

/** The `PrescriptionRepository` adapter. */
@Injectable()
export class PrismaPrescriptionRepository implements PrescriptionRepository {
  constructor(private readonly prisma: PrismaService) {}

  /** PR-001, PR-002. The attention within the caller's scope, or `null`. */
  async findEncounterForPrescribing(
    query: EncounterPrescriptionsQuery,
  ): Promise<PrescribingEncounter | null> {
    const encounter = await this.prisma.encounter.findFirst({
      where: { id: query.encounterId, ...encounterSiteFilter(query.sites) },
      select: {
        id: true,
        siteId: true,
        patientId: true,
        status: true,
        startedAt: true,
      },
    });
    return encounter;
  }

  /**
   * PR-004, PR-034. The caller's clinical identity.
   *
   * The ACESS registration lives on `app_user` and not on `practitioner` —
   * `staff` put it there and this module does not duplicate it — so the read
   * follows the relation rather than copying the column.
   */
  async findPrescriberByUser(
    userId: string,
  ): Promise<PrescriberIdentity | null> {
    const practitioner = await this.prisma.practitioner.findFirst({
      where: { userId, active: true },
      select: {
        id: true,
        user: {
          select: {
            firstName: true,
            lastName: true,
            acessRegistration: true,
            acessExpiresOn: true,
          },
        },
      },
    });
    if (!practitioner) return null;

    return {
      practitionerId: practitioner.id,
      givenName: practitioner.user.firstName,
      familyName: practitioner.user.lastName,
      acessRegistration: practitioner.user.acessRegistration,
      acessExpiresOn: practitioner.user.acessExpiresOn,
    };
  }

  /** PR-003, PR-007 to PR-009. Writes the prescription and its lines. */
  async create(prescription: NewPrescription): Promise<PrescriptionView> {
    const row = await this.prisma.$transaction(async (tx) => {
      /**
       * THE ATTENTION'S ROW, LOCKED FIRST. Agenda locks it FOR UPDATE when
       * reception marks «se fue sin ser atendido» or the doctor annuls the
       * attention; locking it here serialises the two, and every read below
       * —this transaction is READ COMMITTED— sees the attention as it ended
       * up. Without it, a write that read «open» an instant before the
       * annulment committed lands in an annulled attention.
       */
      await tx.$queryRaw`SELECT id FROM "encounter" WHERE id = ${prescription.encounterId}::uuid FOR UPDATE`;

      const encounter = await tx.encounter.findFirst({
        where: {
          id: prescription.encounterId,
          ...encounterSiteFilter(prescription.sites),
        },
        select: { id: true, siteId: true, status: true },
      });
      if (!encounter) throw new PrescriptionEncounterNotFoundError();
      // PR-002, judged again on the locked row: the service's check ran before
      // this transaction and could be stale.
      if (!admitsPrescribing(encounter.status)) {
        throw new PrescriptionEncounterNotOpenError(encounter.status);
      }

      /**
       * PR-007, PR-008. Every concept resolved in ONE statement inside this
       * transaction: which catalogue it is from, what it is called, and whether
       * it was in force on the CLINICAL DATE of the attention.
       */
      const concepts = await conceptsForEncounter(
        tx,
        prescription.encounterId,
        prescription.items
          .map((item) => item.conceptId)
          .filter((id): id is string => id !== null),
      );

      const items = prescription.items.map((item, index) => {
        const line = index + 1;

        // PR-009. Refused here rather than by `prescription_item_off_formulary`
        // so the answer is a sentence about a box instead of a constraint name.
        assertOffFormularyJustified({
          line,
          conceptId: item.conceptId,
          offFormularyJustification: item.offFormularyJustification,
        } as ItemContent);

        if (item.conceptId === null) {
          return {
            conceptId: null,
            // PR-009. Outside the CNMB the caller supplies the name, and the
            // justification is what makes that acceptable.
            genericName: (item.genericName ?? '').trim(),
            ...commonItemFields(item),
          };
        }

        const concept = concepts.get(item.conceptId);
        /**
         * PR-007. A concept that does not exist, one from another catalogue and
         * one retired before the attention answer the SAME refusal, because
         * what the caller does next is identical: pick from the CNMB as it
         * stood that day. The foreign key would refuse the first a moment later
         * with `RELATED_RECORD_MISSING`, which says «falta un registro
         * relacionado» to somebody who chose a medicine.
         */
        if (
          concept === undefined ||
          concept.system_code !== CNMB ||
          !concept.in_force
        ) {
          throw new ConceptNotPrescribableError(line);
        }

        /**
         * PR-070. A narcotic or psychotropic is prescribed on the ACESS's own
         * pre-printed pad, under the doctor's custody, and its original stays
         * at the pharmacy. A document from here would not be that receta, so
         * not even a draft is composed. The mark is
         * `catalog_concept.attributes.controlled`: which medicines carry it
         * comes with the real CNMB (D-084).
         */
        if (concept.controlled) {
          throw new ControlledSubstanceNotPrescribableError(line);
        }

        return {
          conceptId: item.conceptId,
          /**
           * PR-008. THE DCI IS COPIED FROM THE CONCEPT AND NEVER FROM THE
           * REQUEST. In five years the CNMB may have been migrated, pruned or
           * reloaded and the archived prescription still has to say what was
           * prescribed — and that same redundancy is how a lie would get in, so
           * the value can only come from the row read in this transaction.
           */
          genericName: concept.display,
          ...commonItemFields(item),
        };
      });

      return tx.prescription.create({
        data: {
          encounterId: prescription.encounterId,
          prescriberId: prescription.prescriberId,
          // PR-020. `prescription_site_assigned` takes it from the attention
          // whatever is sent; sending the right one keeps Prisma's type honest.
          siteId: encounter.siteId,
          warningSigns: prescription.warningSigns,
          nonPharmacologicalAdvice: prescription.nonPharmacologicalAdvice,
          // PR-003. Born `DRAFT` with no instant, which
          // `prescription_issued_coherence` also guarantees.
          items: { create: items },
        },
        select: PRESCRIPTION_SELECT,
      });
    });

    return toPrescriptionView(row);
  }

  /** PR-006. One prescription within the caller's scope, or `null`. */
  async findById(query: PrescriptionQuery): Promise<PrescriptionView | null> {
    const row = await this.prisma.prescription.findFirst({
      where: { id: query.prescriptionId, ...siteFilter(query.sites) },
      select: PRESCRIPTION_SELECT,
    });
    return row === null ? null : toPrescriptionView(row);
  }

  /** PR-006. The prescriptions of one attention, newest first. */
  async listOfEncounter(
    query: EncounterPrescriptionsQuery,
  ): Promise<PrescriptionView[]> {
    const rows = await this.prisma.prescription.findMany({
      where: { encounterId: query.encounterId, ...siteFilter(query.sites) },
      // Newest first: the one being worked on is the one just written.
      orderBy: { createdAt: 'desc' },
      select: PRESCRIPTION_SELECT,
    });
    return rows.map(toPrescriptionView);
  }

  /** PR-005, PR-021, PR-032, PR-034, PR-060. One issue, one transaction. */
  async issue(
    query: PrescriptionQuery,
    decide: (snapshot: IssueSnapshot) => IssuePlan,
  ): Promise<PrescriptionView> {
    const row = await this.prisma.$transaction(async (tx) => {
      /**
       * THE ATTENTION'S ROW, LOCKED FIRST. Agenda locks it FOR UPDATE when
       * reception marks «se fue sin ser atendido» or the doctor annuls the
       * attention; locking it here serialises the two, and every read below
       * —this transaction is READ COMMITTED— sees the attention as it ended
       * up. Without it, a write that read «open» an instant before the
       * annulment committed lands in an annulled attention.
       * The prescription names its attention, so the lock goes through it.
       */
      await tx.$queryRaw`
        SELECT e.id FROM "encounter" e
          JOIN "prescription" p ON p.encounter_id = e.id
         WHERE p.id = ${query.prescriptionId}::uuid
           FOR UPDATE OF e
      `;

      const current = await tx.prescription.findFirst({
        where: { id: query.prescriptionId, ...siteFilter(query.sites) },
        select: {
          ...PRESCRIPTION_SELECT,
          encounter: {
            select: {
              patientId: true,
              status: true,
              site: { select: { parish: { select: { parentId: true } } } },
            },
          },
          prescriber: {
            select: {
              // PR-040. Of the clinical profile, not of the account.
              emergencyContactPhone: true,
              user: {
                select: { acessRegistration: true, acessExpiresOn: true },
              },
            },
          },
        },
      });
      if (!current) throw new PrescriptionNotFoundError();
      // PR-002. An attention annulled or abandoned while the draft waited
      // issues nothing: the locked row says so.
      if (!admitsPrescribing(current.encounter.status)) {
        throw new PrescriptionEncounterNotOpenError(current.encounter.status);
      }

      const view = toPrescriptionView(current);

      /**
       * PR-021. The city is the CANTON of the site's parish: the DPA is a tree
       * and `site` has no city column (⚠️ **Falta esquema**). Two hops, in the
       * same statement as everything else the decision needs.
       */
      const cantonId = current.encounter.site.parish?.parentId ?? null;
      const canton =
        cantonId === null
          ? null
          : await tx.catalogConcept.findUnique({
              where: { id: cantonId },
              select: { display: true },
            });

      /**
       * PR-060, PR-062. Read HERE and not before: an allergy recorded between
       * the draft and this instant has to refuse the issue.
       *
       * ⚠️ THE ONE ALLERGY READ OF THIS MODULE THAT DOES **NOT** GO THROUGH
       * `ActiveAllergyReader`, AND THE REASON IS THE TRANSACTION. The shared
       * reader takes the pooled client, so its statement would run OUTSIDE this
       * transaction — a read the write cannot see, which is exactly the race
       * this closure exists to close. It runs on `tx` with the SAME predicate:
       * `chartScope` plus `refutedAt: null`. Everywhere else in this module the
       * allergies come from the shared port, so this is the single exception
       * and it is written down rather than left to be discovered.
       */
      const allergies = await tx.patientAllergy.findMany({
        where: {
          ...chartScope(current.encounter.patientId),
          refutedAt: null,
        },
        select: { id: true, substanceConceptId: true, substanceText: true },
      });

      /**
       * PR-070 AGAIN, AT THE ISSUE: «no generar, imprimir NI NUMERAR». A
       * draft composed before its concept carried the mark would otherwise
       * take a number of the ACESS series here.
       *
       * ⚠️ IT READS THE LINE'S OWN CONCEPT. A CNMB republication that creates
       * a NEW version of the concept (D-084) is not seen through an old draft;
       * when the real import exists, this has to look up the code in force.
       */
      const conceptIds = view.items
        .map((item) => item.conceptId)
        .filter((id): id is string => id !== null);
      if (conceptIds.length > 0) {
        const controlled = new Set(
          (
            await tx.$queryRaw<{ id: string }[]>`
              SELECT id::text AS id FROM catalog_concept
               WHERE id = ANY(${conceptIds}::uuid[])
                 AND (attributes ->> 'controlled') = 'true'
            `
          ).map((row) => row.id),
        );
        const line = view.items.findIndex(
          (item) => item.conceptId !== null && controlled.has(item.conceptId),
        );
        if (line >= 0)
          throw new ControlledSubstanceNotPrescribableError(line + 1);
      }

      const plan = decide({
        status: view.status,
        warningSigns: view.warningSigns,
        nonPharmacologicalAdvice: view.nonPharmacologicalAdvice,
        items: view.items.map(toItemContent),
        allergies,
        cityOfPrescription: canton?.display ?? null,
        prescriber: {
          acessRegistration: current.prescriber.user.acessRegistration,
          acessExpiresOn: current.prescriber.user.acessExpiresOn,
          contactPhone: current.prescriber.emergencyContactPhone,
        },
      });

      /**
       * PR-005. CONDITIONAL ON THE STATUS THAT WAS READ. Two people who both
       * read `DRAFT` and both decide cannot both write: the loser matches zero
       * rows and is refused with the WINNER's status, never with a stale
       * acceptance that would issue the same prescription twice with two
       * verification codes.
       */
      const updated = await tx.prescription.updateMany({
        where: { id: query.prescriptionId, status: 'DRAFT' },
        data: {
          status: 'ACTIVE',
          issuedAt: plan.issuedAt,
          verificationCode: plan.verificationCode,
        },
      });
      if (updated.count === 0) {
        throw new PrescriptionNotEditableError(
          await currentStatus(tx, query.prescriptionId),
        );
      }

      return tx.prescription.findUniqueOrThrow({
        where: { id: query.prescriptionId },
        select: PRESCRIPTION_SELECT,
      });
    });

    return toPrescriptionView(row);
  }

  /**
   * PR-010. Annuls an ISSUED prescription. NOTHING IS DELETED.
   *
   * ⚠️ CONDITIONAL ON `ACTIVE` AND NOT ON `DRAFT`, and it is
   * `prescription_issued_coherence` that decides it: every state other than
   * `DRAFT` requires an instant of issue, so a draft cannot become `CANCELLED`
   * at all. Art. 70 describes the same act — the emitted receta that was lost
   * or altered — so the schema and the norm agree here. See the service.
   */
  async cancel(
    query: PrescriptionQuery,
    decide: (status: PrescriptionStatus) => void,
  ): Promise<PrescriptionView> {
    const row = await this.prisma.$transaction(async (tx) => {
      const current = await tx.prescription.findFirst({
        where: { id: query.prescriptionId, ...siteFilter(query.sites) },
        select: { id: true, status: true },
      });
      if (!current) throw new PrescriptionNotFoundError();

      decide(current.status);

      const updated = await tx.prescription.updateMany({
        where: { id: query.prescriptionId, status: 'ACTIVE' },
        data: { status: 'CANCELLED' },
      });
      if (updated.count === 0) {
        throw new PrescriptionNotEditableError(
          await currentStatus(tx, query.prescriptionId),
        );
      }

      return tx.prescription.findUniqueOrThrow({
        where: { id: query.prescriptionId },
        select: PRESCRIPTION_SELECT,
      });
    });

    return toPrescriptionView(row);
  }

  /**
   * PR-011. Discards a DRAFT. NOTHING IS DELETED.
   *
   * ⚠️ CONDITIONAL ON `DRAFT`, which is also what
   * `prescription_discard_only_from_draft` says in the database: `discarded_at
   * IS NULL OR status = 'DISCARDED'` makes the instant and the state one fact,
   * and the reworked `prescription_issued_coherence` keeps `DISCARDED` on the
   * side of the states with NO instant of issue. So an emitted prescription
   * cannot be discarded even by a writer that never came through here — it is
   * annulled, which is the other act.
   *
   * ⚠️ AND THE THREE COLUMNS ARE WRITTEN TOGETHER. `prescription_discard_
   * states_who_when_and_why` refuses the row otherwise, and that is the point:
   * discarding without saying why is a way of making what was written vanish.
   */
  async discard(
    query: PrescriptionQuery,
    plan: DiscardPlan,
    decide: (status: PrescriptionStatus) => void,
  ): Promise<PrescriptionView> {
    const row = await this.prisma.$transaction(async (tx) => {
      const current = await tx.prescription.findFirst({
        where: { id: query.prescriptionId, ...siteFilter(query.sites) },
        select: { id: true, status: true },
      });
      if (!current) throw new PrescriptionNotFoundError();

      decide(current.status);

      const updated = await tx.prescription.updateMany({
        where: { id: query.prescriptionId, status: 'DRAFT' },
        data: {
          status: 'DISCARDED',
          discardedAt: plan.discardedAt,
          discardedById: plan.discardedById,
          discardReason: plan.discardReason,
        },
      });
      if (updated.count === 0) {
        throw new PrescriptionNotEditableError(
          await currentStatus(tx, query.prescriptionId),
        );
      }

      return tx.prescription.findUniqueOrThrow({
        where: { id: query.prescriptionId },
        select: PRESCRIPTION_SELECT,
      });
    });

    return toPrescriptionView(row);
  }

  /**
   * PR-020 to PR-040. Everything the printed prescription carries.
   *
   * ONE STATEMENT AND NOT FIVE, because the answers have to describe the same
   * instant. Prisma resolves the nested selections as joins (`relationJoins`
   * is on, see the header of `schema.prisma`).
   *
   * ⚠️ THE ALLERGIES ARE NOT HERE (PR-027, PR-062). They come from
   * `ActiveAllergyReader`, the one statement in the system that resolves «la
   * ficha y las que absorbió»: a nested copy of that predicate here would be a
   * second chance to forget the merge link, and the half it would drop is the
   * penicillin of the absorbed chart. What this returns is `chartId`, and the
   * service asks the reader with it.
   */
  async documentOf(
    query: PrescriptionQuery,
  ): Promise<PrescriptionRecordSource | null> {
    const row = await this.prisma.prescription.findFirst({
      where: { id: query.prescriptionId, ...siteFilter(query.sites) },
      select: {
        ...PRESCRIPTION_SELECT,
        encounter: {
          select: {
            patientId: true,
            ageYears: true,
            ageMonths: true,
            ageDays: true,
            site: {
              select: {
                id: true,
                name: true,
                mspUnicode: true,
                parish: { select: { parent: { select: { display: true } } } },
              },
            },
            // PR-026. The diagnoses of the attention, principal first, with the
            // code and description `trg_diagnosis_snapshot` froze.
            diagnoses: {
              orderBy: [{ rank: 'asc' }, { recordedAt: 'asc' }],
              select: { cie10Code: true, cie10Display: true },
            },
            /**
             * PR-024. The name only, and NOT the allergies (PR-027): those are
             * `ActiveAllergyReader`'s, so «la ficha y las que absorbió» is one
             * statement for the whole system instead of one per module.
             */
            patient: { select: { familyName: true, givenName: true } },
          },
        },
        prescriber: {
          select: {
            emergencyContactPhone: true,
            user: {
              select: {
                firstName: true,
                lastName: true,
                acessRegistration: true,
              },
            },
          },
        },
      },
    });
    if (row === null) return null;

    const chart = row.encounter.patient;

    return {
      prescription: toPrescriptionView(row),
      // PR-027, PR-062. The service asks `ActiveAllergyReader` with this.
      chartId: row.encounter.patientId,
      site: {
        id: row.encounter.site.id,
        name: row.encounter.site.name,
        mspUnicode: row.encounter.site.mspUnicode,
        // PR-021. The canton of the parish, which is «la ciudad» of art. 5.a.ii.
        city: row.encounter.site.parish?.parent?.display ?? null,
      },
      patient: {
        familyName: chart.familyName,
        givenName: chart.givenName,
        // PR-025. The FROZEN age of the attention, never today's.
        ageYears: row.encounter.ageYears,
        ageMonths: row.encounter.ageMonths,
        ageDays: row.encounter.ageDays,
      },
      diagnoses: row.encounter.diagnoses.map((diagnosis) => ({
        code: diagnosis.cie10Code,
        display: diagnosis.cie10Display,
      })),
      prescriber: {
        givenName: row.prescriber.user.firstName,
        familyName: row.prescriber.user.lastName,
        acessRegistration: row.prescriber.user.acessRegistration,
        contactPhone: row.prescriber.emergencyContactPhone,
      },
    };
  }
}

/** PR-005. The state a losing writer has to be told about. */
async function currentStatus(
  tx: Prisma.TransactionClient,
  prescriptionId: string,
): Promise<PrescriptionStatus> {
  const row = await tx.prescription.findUniqueOrThrow({
    where: { id: prescriptionId },
    select: { status: true },
  });
  return row.status;
}

/**
 * PR-007, PR-008. Everything one statement can say about a set of concepts in
 * the context of an attention.
 *
 * ⚠️ RAW SQL BECAUSE OF ONE COLUMN. `catalog_concept.valid_period` is a
 * `daterange` generated by a manual migration and Prisma models it as
 * `Unsupported`, so `@>` cannot be expressed through the client. Writing the
 * containment here rather than reading `valid_from`/`valid_to` and comparing in
 * TypeScript is deliberate: `trg_diagnosis_concept_in_force` uses `@>` on the
 * generated column, and two statements of one predicate is how they end up
 * disagreeing about the last day a code was valid.
 *
 * ⚠️ AND THE DATE IS RESOLVED IN `America/Guayaquil`. A bare `::date` over a
 * `timestamptz` uses the SESSION's zone, so a medicine prescribed at 20:00 on
 * the last day a CNMB entry was in force would be checked against the following
 * day and refused — the defect
 * `20260806040611_clinical_date_in_ecuador_timezone` exists to have fixed.
 */
async function conceptsForEncounter(
  tx: Prisma.TransactionClient,
  encounterId: string,
  conceptIds: readonly string[],
): Promise<Map<string, ConceptRow>> {
  if (conceptIds.length === 0) return new Map();

  const rows = await tx.$queryRaw<ConceptRow[]>`
    SELECT cc."id"::text      AS id,
           cs."code"::text    AS system_code,
           cc."display"::text AS display,
           (cc."valid_period" @> (e."started_at" AT TIME ZONE 'America/Guayaquil')::date)
                              AS in_force,
           (cc."attributes" ->> 'controlled') = 'true'
                              AS controlled
      FROM "encounter" AS e
      JOIN "catalog_concept" AS cc
        ON cc."id" = ANY(${[...new Set(conceptIds)]}::uuid[])
      JOIN "catalog_system" AS cs ON cs."id" = cc."system_id"
     WHERE e."id" = ${encounterId}::uuid
  `;

  return new Map(rows.map((row) => [row.id, row]));
}

/**
 * PR-006, PR-091. The caller's resolved scope as a `where` fragment on the
 * prescription, narrowed THROUGH the attention.
 *
 * `prescription` has no site of its own: reading through the relation is what
 * keeps the prescriptions of another site's attention from answering a caller
 * who cannot open the attention itself — which is art. 10 made into a filter.
 *
 * `'all'` yields no filter, and an empty list never reaches here: `siteScope`
 * in `shared/authorisation` throws `SITE_SCOPE_DENIED` when the caller holds
 * the permission at no site, precisely so «no filter to apply» can never be
 * spelled as «every site».
 */
function siteFilter(sites: SiteScopeFilter): Prisma.PrescriptionWhereInput {
  return sites === 'all' ? {} : { encounter: { siteId: { in: [...sites] } } };
}

/** The same scope when the row being read IS the attention. */
function encounterSiteFilter(
  sites: SiteScopeFilter,
): Prisma.EncounterWhereInput {
  return sites === 'all' ? {} : { siteId: { in: [...sites] } };
}

/** The fields a line carries whether or not it names a CNMB concept. */
function commonItemFields(item: {
  presentation: string | null;
  concentration: string | null;
  routeCode: string | null;
  quantity: number | null;
  doseText: string | null;
  frequencyText: string | null;
  durationDays: number | null;
  instructions: string | null;
  offFormularyJustification: string | null;
}) {
  return {
    presentation: item.presentation,
    concentration: item.concentration,
    routeCode: item.routeCode,
    quantity: item.quantity,
    // `dose_text` and `frequency_text` are NOT NULL in the schema, so a draft
    // written without them stores the empty string and PR-032 refuses the ISSUE
    // by field. Refusing at composition time is what EN-020 argues against.
    doseText: item.doseText ?? '',
    frequencyText: item.frequencyText ?? '',
    durationDays: item.durationDays,
    instructions: item.instructions,
    offFormularyJustification: item.offFormularyJustification,
  };
}

/** A `prescription` row and its lines, as the domain reads them. */
function toPrescriptionView(row: PrescriptionRow): PrescriptionView {
  return {
    id: row.id,
    encounterId: row.encounterId,
    prescriberId: row.prescriberId,
    status: row.status,
    issuedAt: row.issuedAt,
    verificationCode: row.verificationCode,
    sequenceNumber: row.sequenceNumber,
    warningSigns: row.warningSigns,
    nonPharmacologicalAdvice: row.nonPharmacologicalAdvice,
    createdAt: row.createdAt,
    discardedAt: row.discardedAt,
    discardReason: row.discardReason,
    items: row.items.map((item, index) => ({
      id: item.id,
      // The 1-based address every message uses (PR-032, PR-094).
      line: index + 1,
      conceptId: item.conceptId,
      genericName: item.genericName,
      presentation: item.presentation,
      concentration: item.concentration,
      routeCode: item.routeCode,
      // `Decimal(10,2)` out of the driver: a number is what the domain spells
      // in words, and the scale is small enough that nothing is lost.
      quantity: item.quantity === null ? null : item.quantity.toNumber(),
      doseText: item.doseText,
      frequencyText: item.frequencyText,
      durationDays: item.durationDays,
      instructions: item.instructions,
      offFormularyJustification: item.offFormularyJustification,
    })),
  };
}

/** PR-032. One line as the content rules of art. 5.c see it. */
function toItemContent(item: PrescriptionView['items'][number]): ItemContent {
  return {
    line: item.line,
    genericName: item.genericName,
    presentation: item.presentation,
    concentration: item.concentration,
    routeCode: item.routeCode,
    quantity: item.quantity,
    doseText: item.doseText,
    frequencyText: item.frequencyText,
    durationDays: item.durationDays,
    conceptId: item.conceptId,
    offFormularyJustification: item.offFormularyJustification,
  };
}
